services:
  App\Tests\Resources\:
    resource: '../../tests/Resources/'

  App\Tests\Resources\Fixtures\:
    resource: '../../tests/Resources/Fixtures/*'
    tags: [ 'doctrine.fixture.orm' ]
    autowire: true

  App\Tests\Resources\Factory\:
    resource: '../../tests/Resources/Factory/*'
    autowire: true
