version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - keyscom
  php:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile-php
    volumes:
      - symfony-docker-vendor-sync:/var/www/html/vendor:nocopy
      - symfony-docker-app-sync:/var/www/html:nocopy
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    networks:
      - keyscom
      - keyscom-network
    depends_on:
      - postgres
  postgres:
    build:
      context: ./.docker/db
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env.local
    networks:
      - keyscom
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "8081:8025" # web ui
    networks:
      - keyscom

networks:
  keyscom:
  keyscom-network:
    external: true
volumes:
  symfony-docker-vendor-sync:
    external: true
  symfony-docker-app-sync:
    external: true
